### PR TITLE
Process Feedback Nits

### LINKED ISSUE #98: Fix minor nits in spec from feedback
- [ ] Refer to internal notes for minor typos and writing fixes.

From the [epic description](#97), do:
- [x] system architecture suggestions 1, 2
- [x] operations suggestions 3, 4, 6

### PR DESCRIPTION
**Pull request by indomitableSwan**
- Minor fixes and non-normative/usage notes.
- Clarifications to protocol specifications with respect to inputs/outputs by client and server. This includes adding explicit success indicators as outputs for the server throughout.

Closes #98.

### CODE REVIEW

**Review by vidyaap — COMMENTED** [review]
Looks good to me! I just had two general things:
- question: Why are the server outputs in cryptographic_flows not whatever the server returns to the client (instead of just the success indicator)?
- nit: could you update the links to the "retrieve_storage_key" section? I think we want "#retrieve_storage_key-protocol" instead of "#retrievestoragekey-functionality". Thanks!

**Comment by indomitableSwan** [comment]
> Looks good to me! I just had two general things:
> 
> * question: Why are the server outputs in cryptographic_flows not whatever the server returns to the client (instead of just the success indicator)?

Good question. I didn't include those outputs because the server shouldn't be doing anything with those values at that point in the protocol, i.e., I included a success indicator because that seemed useful for server logging, debugging and security.

We could also have the outputs be whatever the server is supposed to store, but I didn't do this because storage happens at different places in the protocol execution, and ideally, the server doesn't wait to take those actions.

What would you recommend here?

> * nit: could you update the links to the "retrieve_storage_key" section? I think we want "#retrieve_storage_key-protocol" instead of "#retrievestoragekey-functionality". Thanks!

Will do.

**Review by vidyaap — APPROVED** [review]
> Good question. I didn't include those outputs because the server shouldn't be doing anything with those values at that point in the protocol, i.e., I included a success indicator because that seemed useful for server logging, debugging and security [...]

The success indicator makes sense! It would be nice to add what the server returns to the client as an output, but that may mess with the way you have the steps written out right now. I think both ways make sense, so I'll leave that up to you!

Otherwise, looks good, thank you!

**Comment by indomitableSwan** [comment]
> > Good question. I didn't include those outputs because the server shouldn't be doing anything with those values at that point in the protocol, i.e., I included a success indicator because that seemed useful for server logging, debugging and security [...]
> 
> The success indicator makes sense! It would be nice to add what the server returns to the client as an output, but that may mess with the way you have the steps written out right now. I think both ways make sense, so I'll leave that up to you!
> 

OK, I'll leave this as future conversation then. I'm always a little unclear of what the best ways are of handling these things --- still not sure why we would want to have server outputs that the server then doesn't do anything with. Is it for testing? Maybe that's more of an implementation detail than something the protocol writeup needs to be prescriptive about?

> Otherwise, looks good, thank you!

**Pull request merged**
